version: '2'

services:
  app:
      build: ./flask_app
      links:
        - db
      ports:
        - "5000:5000"
      networks:
        - tt
      volumes:
        - './flask_app:/flask_app/'
  db:
    restart: always
    image: postgres:10.5
    container_name: tt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd@1
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - TZ=Asia/Manila
    volumes:
      - ./docker/db/dbini:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tt

networks:
  tt:
